import { useState } from "react";
import "./Reports.css";

function Reports({ onBack }) {
  const [showGenerate, setShowGenerate] = useState(false);

  const [reports, setReports] = useState([
    {
      name: "Sales Performance Report",
      type: "Sales",
      date: "11 Aug 2026",
      owner: "Admin",
      status: "Completed",
    },
    {
      name: "Employee Performance Report",
      type: "Employee",
      date: "10 Aug 2026",
      owner: "HR Manager",
      status: "Completed",
    },
    {
      name: "Customer Activity Report",
      type: "Customer",
      date: "09 Aug 2026",
      owner: "Sales Manager",
      status: "Completed",
    },
    {
      name: "Financial Summary Report",
      type: "Finance",
      date: "08 Aug 2026",
      owner: "Finance Manager",
      status: "Pending",
    },
    {
      name: "Monthly Business Report",
      type: "Business",
      date: "01 Aug 2026",
      owner: "Admin",
      status: "Completed",
    },
  ]);

  const [reportName, setReportName] = useState("");
  const [reportType, setReportType] = useState("Sales");

  // Search and filter
  const [search, setSearch] = useState("");
  const [filterType, setFilterType] = useState("All Reports");

  // =========================
  // GENERATE REPORT
  // =========================
  const handleGenerate = () => {
    if (!reportName.trim()) {
      alert("Please enter a report name.");
      return;
    }

    const newReport = {
      name: reportName.trim(),
      type: reportType,
      date: "11 Aug 2026",
      owner: "Admin",
      status: "Completed",
    };

    setReports((previousReports) => [
      newReport,
      ...previousReports,
    ]);

    setReportName("");
    setReportType("Sales");
    setShowGenerate(false);

    alert("Report generated successfully!");
  };

  // =========================
  // DOWNLOAD REPORT
  // =========================
  const handleDownload = (report) => {
    const content = `
FUNDSROOM ERP-CRM
--------------------------------

REPORT DETAILS

Report Name : ${report.name}
Report Type : ${report.type}
Date        : ${report.date}
Owner       : ${report.owner}
Status      : ${report.status}

--------------------------------
Generated by Fundsroom ERP-CRM
`;

    const blob = new Blob([content], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = `${report.name.replace(
      /[^a-z0-9]/gi,
      "_"
    )}.txt`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  // =========================
  // VIEW REPORT
  // =========================
  const handleView = (report) => {
    alert(
      `REPORT DETAILS\n\n` +
        `Name: ${report.name}\n` +
        `Type: ${report.type}\n` +
        `Date: ${report.date}\n` +
        `Owner: ${report.owner}\n` +
        `Status: ${report.status}`
    );
  };

  // =========================
  // SEARCH + FILTER
  // =========================
  const filteredReports = reports.filter((report) => {
    const matchesSearch = report.name
      .toLowerCase()
      .includes(search.toLowerCase());

    const matchesType =
      filterType === "All Reports" ||
      report.type === filterType;

    return matchesSearch && matchesType;
  });

  return (
    <div className="reports-page">

      {/* BACK BUTTON */}
      <button
        className="back-btn"
        onClick={onBack}
      >
        ← Back
      </button>

      {/* ================= HEADER ================= */}
      <div className="reports-header">

        <div className="reports-title">

          <p className="reports-label">
            ERP • CRM MANAGEMENT SYSTEM
          </p>

          <h1>
            📊 Reports
          </h1>

          <p>
            Generate, view and manage your business reports.
          </p>

        </div>

        <button
          className="generate-report-btn"
          onClick={() => setShowGenerate(true)}
        >
          + Generate Report
        </button>

      </div>

      {/* ================= STATISTICS ================= */}
      <div className="report-summary">

        <div className="report-card">
          <div className="report-card-title">
            Total Reports
          </div>

          <div className="report-card-number">
            {reports.length}
          </div>

          <div className="report-card-text">
            All generated reports
          </div>
        </div>

        <div className="report-card">
          <div className="report-card-title">
            Completed
          </div>

          <div className="report-card-number">
            {
              reports.filter(
                (r) => r.status === "Completed"
              ).length
            }
          </div>

          <div className="report-card-text">
            Successfully generated
          </div>
        </div>

        <div className="report-card">
          <div className="report-card-title">
            Pending
          </div>

          <div className="report-card-number">
            {
              reports.filter(
                (r) => r.status === "Pending"
              ).length
            }
          </div>

          <div className="report-card-text">
            Reports in progress
          </div>
        </div>

        <div className="report-card">
          <div className="report-card-title">
            Report Types
          </div>

          <div className="report-card-number">
            5
          </div>

          <div className="report-card-text">
            Business categories
          </div>
        </div>

      </div>

      {/* ================= REPORT LIST ================= */}
      <div className="reports-container">

        <div className="reports-top">

          <div>
            <h2>Report List</h2>

            <p>
              View and manage your business reports.
            </p>
          </div>

          {/* SEARCH + FILTER */}
          <div className="report-filters">

            <input
              type="text"
              placeholder="🔍 Search reports..."
              value={search}
              onChange={(e) =>
                setSearch(e.target.value)
              }
            />

            <select
              value={filterType}
              onChange={(e) =>
                setFilterType(e.target.value)
              }
            >
              <option value="All Reports">
                All Reports
              </option>

              <option value="Sales">
                Sales
              </option>

              <option value="Employee">
                Employee
              </option>

              <option value="Customer">
                Customer
              </option>

              <option value="Finance">
                Finance
              </option>

              <option value="Business">
                Business
              </option>
            </select>

          </div>

        </div>

        {/* ================= TABLE ================= */}
        <div className="reports-table-wrapper">

          <table className="reports-table">

            <thead>
              <tr>
                <th>Report</th>
                <th>Type</th>
                <th>Date</th>
                <th>Owner</th>
                <th>Status</th>
                <th>Action</th>
              </tr>
            </thead>

            <tbody>

              {filteredReports.length === 0 ? (

                <tr>
                  <td
                    colSpan="6"
                    className="no-reports"
                  >
                    No reports found.
                  </td>
                </tr>

              ) : (

                filteredReports.map(
                  (report, index) => (

                    <tr key={index}>

                      {/* REPORT */}
                      <td className="report-name">
                        📄 {report.name}
                      </td>

                      {/* TYPE */}
                      <td>
                        <span className="report-type">
                          {report.type}
                        </span>
                      </td>

                      {/* DATE */}
                      <td>
                        {report.date}
                      </td>

                      {/* OWNER */}
                      <td>
                        {report.owner}
                      </td>

                      {/* STATUS */}
                      <td>
                        <span
                          className={
                            report.status ===
                            "Completed"
                              ? "report-status completed"
                              : "report-status pending"
                          }
                        >
                          ● {report.status}
                        </span>
                      </td>

                      {/* ACTION */}
                      <td className="report-actions">

                        <button
                          className="view-report-btn"
                          onClick={() =>
                            handleView(report)
                          }
                        >
                          View
                        </button>

                        <button
                          className="download-report-btn"
                          onClick={() =>
                            handleDownload(report)
                          }
                        >
                          Download
                        </button>

                      </td>

                    </tr>

                  )
                )

              )}

            </tbody>

          </table>

        </div>

      </div>

      {/* ================= GENERATE MODAL ================= */}
      {showGenerate && (

        <div
          className="modal-overlay"
          onClick={() =>
            setShowGenerate(false)
          }
        >

          <div
            className="modal"
            onClick={(e) =>
              e.stopPropagation()
            }
          >

            <h2>
              Generate New Report
            </h2>

            <p className="modal-subtitle">
              Create a new business report.
            </p>

            <label>
              Report Name
            </label>

            <input
              type="text"
              placeholder="Enter report name"
              value={reportName}
              onChange={(e) =>
                setReportName(e.target.value)
              }
            />

            <label>
              Report Type
            </label>

            <select
              value={reportType}
              onChange={(e) =>
                setReportType(e.target.value)
              }
            >
              <option value="Sales">
                Sales
              </option>

              <option value="Employee">
                Employee
              </option>

              <option value="Customer">
                Customer
              </option>

              <option value="Finance">
                Finance
              </option>

              <option value="Business">
                Business
              </option>
            </select>

            <div className="modal-buttons">

              <button
                className="cancel-btn"
                onClick={() =>
                  setShowGenerate(false)
                }
              >
                Cancel
              </button>

              <button
                className="generate-modal-btn"
                onClick={handleGenerate}
              >
                Generate Report
              </button>

            </div>

          </div>

        </div>

      )}

    </div>
  );
}

export default Reports;